spring:
  application:
    name: currency-exchange
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8000
