spring:
  application:
    name: currency-exchange
#  cloud:
#    config:
#      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
#      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
#    burada baslangicta db veri eklemesi icin true yaptik
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
server:
  port: 8000

